apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbmanagements.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseType:
                  type: string
                  enum:
                    - postgresql
                    - mysql
                action:
                  type: string
                  enum:
                    - backup
                    - restore
                    - shard
                    - scale
                parameters:
                  type: object
                  additionalProperties: true
  scope: Namespaced
  names:
    plural: dbmanagements
    singular: dbmanagement
    kind: DBManagement
    shortNames:
      - dbm
