# Utiliser une image de base Python officielle.
FROM python:3.8-slim

# Définir le répertoire de travail dans le conteneur.
WORKDIR /app

# Copier le script du scheduler extender dans le conteneur.
COPY scheduler-extender.py /app/scheduler-extender.py

# Installer Flask, nécessaire pour exécuter l'application web.
RUN pip install flask

# Exposer le port sur lequel le scheduler extender écoute.
EXPOSE 12345

# Définir la commande par défaut pour démarrer l'application.
CMD ["python", "scheduler-extender.py"]
