apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: vote
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "10"
    limits.memory: "10Gi"
