apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-ui
  name: result-ui
  namespace: vote  # Ajouté pour s'assurer qu'il se trouve dans le namespace "vote"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
        - image: voting/result-ui:v1.0.15
          name: result-ui
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 80
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi 
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false  # Sécurité ajoutée
            readOnlyRootFilesystem: true     # Sécurité ajoutée
            seccompProfile:
              type: RuntimeDefault            # Sécurité ajoutée
          volumeMounts:
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
      volumes:
      - name: run
        emptyDir: {}
      - name: cache
        emptyDir: {}
