apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: vote
spec:
  secretName: webhook-cert
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: mutating-webhook.vote.svc
  dnsNames:
    - mutating-webhook
    - mutating-webhook.vote
    - mutating-webhook.vote.svc
    - mutating-webhook.vote.svc.cluster.local
