apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote  # Ajouté pour s'assurer qu'il se trouve dans le namespace "vote"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: voting/result:v1.0.16
          name: result
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
            tcpSocket:
              port: 5000
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi 
          securityContext:
            allowPrivilegeEscalation: false  # Sécurité ajoutée
            # readOnlyRootFilesystem: true   # Peut être ajouté pour plus de sécurité
            # runAsUser: 10000               # Peut être ajouté pour plus de sécurité
            # runAsNonRoot: true             # Peut être ajouté pour plus de sécurité
            seccompProfile:
              type: RuntimeDefault            # Sécurité ajoutée
            capabilities:
              drop:
              - ALL                           # Sécurité ajoutée
