apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-vote-api-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: go-vote-api-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: go-vote-api-clusterrole
  apiGroup: rbac.authorization.k8s.io
