apiVersion: v1
kind: Service
metadata:
  name: go-vote-api
  namespace: default
  labels:
    app: go-vote-api
spec:
  selector:
    app: go-vote-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
