apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-aggregator-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
