apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:endpoint-slice-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:endpointslice-controller
subjects:
- kind: ServiceAccount
  name: endpoint-slice-controller
  namespace: kube-system
