apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-aggregator-role-binding
subjects:
- kind: ServiceAccount
  name: api-aggregator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: api-aggregator-role
  apiGroup: rbac.authorization.k8s.io
