---
# Source: votingapp/templates/result-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: result-ui
spec:
  type: NodePort
  ports:
    - name: "result-ui-service"
      port: 80
      targetPort: 80
      nodePort: 31001
  selector:
    app: result-ui
