# Utiliser une image Python de base
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY webhook.py /app/webhook.py

# Installer Flask
RUN pip install Flask

# Copier les certificats dans le conteneur
COPY server.crt /app/server.crt
COPY server.key /app/server.key

# Exposer le port 443
EXPOSE 443

# Définir la commande par défaut pour exécuter l'application
CMD ["python", "webhook.py"]
